### ISSUE TITLE
Nominate myself @oeular as a Review member

### ISSUE THREAD

**Issue by oeular** [kubevela/community#10]
I has been actively contributing to KubeVela, and three of his pull requests have been merged.

kubevela/kubevela.io#596
kubevela/catalog#325
kubevela/catalog#337

I has met the requirement for the Review role of KubeVela membership. So nominate myself as a Review member.
Please sponsor me with 👍.

**Comment by wonderflow** [comment]
great work 👍🏻

**Comment by fourierr** [comment]
lgtm

**Comment by leejanee** [comment]
good job👍🏻
