### ISSUE TITLE
Apply for Approver Role

### ISSUE THREAD

**Issue by Hanmengnan** [kubevela/community#100]
I would like to nominate myself as an approver of KubeVela.

I'd be honored if I can continue my contributions as an approver and committed to make the community better.

These are my contributions:

1. [Feat: add the user doc of `vela top`](https://github.com/kubevela/kubevela.io/pull/985)
2. [Feat: `vela top` supports custom theme features](https://github.com/kubevela/kubevela/pull/5180)
3. [[example] Add a video example of Keda's autoscaling in CPU based trigger.](https://github.com/kubevela/catalog/pull/560)
4. [Feat: Introduce timeout mechanism into cache and update network request mechanism in `vela top`](https://github.com/kubevela/kubevela/pull/5153)
5. [Fix: fix the stuck problem and use LRU cache to promote the speed of loading topology](https://github.com/kubevela/kubevela/pull/5002)
6. [Fix: fix problem of loading pods of cronjob](https://github.com/kubevela/kubevela/pull/5007)
7. [Fix: can't obtain pods generated by `Crontask` component (patch of PR 4925)](https://github.com/kubevela/kubevela/pull/4942)
8. [Fix: can't get pods of CronTask component ](https://github.com/kubevela/kubevela/pull/4925)
9. [Feat: add the container view to `vela top`](https://github.com/kubevela/kubevela/pull/4892)
10. [Feat: add the feature of viewing log of pod in `vela top`](https://github.com/kubevela/kubevela/pull/4870)
11. [Feat: add resource topology view in `vela top`](https://github.com/kubevela/kubevela/pull/4817)
12. [Feat: Add more data field to application view and managed resource view in vela top](https://github.com/kubevela/kubevela/pull/4781)
13. [Fix: fix the bug that the empty row exists in cluster view in `vela  top`](https://github.com/kubevela/kubevela/pull/4772)
14. [Feat: add feature of refreshing resource view and fix the bug of stucking](https://github.com/kubevela/kubevela/pull/4743)
15. [Docs: add the design document of vela-top](https://github.com/kubevela/kubevela/pull/4736)
16. [Refactor: rename interfaces and functions in `vela top` to promote semanticity](https://github.com/kubevela/kubevela/pull/4727)
17. [Fix: fix the `vela system info` command can not work](https://github.com/kubevela/kubevela/pull/4713)
18. [Feat: highlight the Yaml text of `vela top`](https://github.com/kubevela/kubevela/pull/4689)
19. [Refactor: refactor the source of all kinds of views, use the "Factory Method" design patterns to rewrite the code to upgrade the quality of code](https://github.com/kubevela/kubevela/pull/4679)
20. [Feat: add filtering features to the `Application` view and `K8S object` view of `vela top`](https://github.com/kubevela/kubevela/pull/4612)
21. [Feat: load the Yaml text of resource in `vela top`](https://github.com/kubevela/kubevela/pull/4665)
22. [Feat: add a new resource level view: `Pod view` to `vela top`](https://github.com/kubevela/kubevela/pull/4661)
23. [Feat: add new system info to system info board and optimize code](https://github.com/kubevela/kubevela/pull/4640)
24. [Feat: Add a new CLI command: `vela top` which can display system information and resource status in UI form](https://github.com/kubevela/kubevela/pull/4556)
25. [Docs: translation of migration-from-old-version(#808)](https://github.com/kubevela/kubevela.io/pull/843)
26. [Feat: load the system version requirements from the addon's meta.yaml(#395)](https://github.com/kubevela/catalog/pull/397)
27. [Feat: search useful addon version automatically](https://github.com/kubevela/kubevela/pull/4232)
28. [Fix: add handle of ".yml" type in readviewfile function](https://github.com/kubevela/kubevela/pull/4172)
29. [Feat: add the feature that views in addon are applied independently.(#3905)](https://github.com/kubevela/kubevela/pull/4154)

**Comment by wonderflow** [comment]
Great job!  +1

**Comment by Somefive** [comment]
LGTM

**Comment by FogDong** [comment]
Thanks for contributing! LGTM.

**Comment by barnettZQG** [comment]
@Hanmengnan  Good job!  +1.  Let's make the vela CLI command be better.

**Comment by chivalryq** [comment]
LGTM. You make vela CLI better!

**Comment by wangyikewxgm** [comment]
LGTM

**Comment by wonderflow** [comment]
@Hanmengnan Congratulations! You can send a PR to the OWNERS file.

**Comment by jefree-cat** [comment]
Congratulations! LGTM.

**Comment by Hanmengnan** [comment]
Thank you all so much for your support!
