### ISSUE TITLE
Apply for Reviewer Role

### ISSUE THREAD

**Issue by suwliang3** [kubevela/community#104]
I would like to nominate myself as a reviewer of KubeVela.

I'd be honored if I can continue my contributions as a reviewer and committed to make the community better.

These are my contributions:
1、[fix: Determine which clusters to be installed by parameters](https://github.com/kubevela/kubevela.io/pull/1082)
2、[Feat: Detect the correctness of the custom addon repository](https://github.com/kubevela/kubevela/pull/5221)
3、[Feat: rollout support statefulsets](https://github.com/kubevela/kubevela/pull/5202)
4、[Feat: return notFound error when deleting app](https://github.com/kubevela/kubevela/pull/5189)
5、[[addon velaux] add event-view](https://github.com/kubevela/catalog/pull/580)
6、[[addon istio] Modify the workflow of canary-rollback](https://github.com/kubevela/catalog/pull/570)
7、[[Addon istio]Modify the label of destinationrules](https://github.com/kubevela/catalog/pull/563)

**Comment by wonderflow** [comment]
+1 Thanks for your great contributions!

**Comment by Hanmengnan** [comment]
LGTM

**Comment by barnettZQG** [comment]
+1 Happy work with you to make KubeVela better.

**Comment by FogDong** [comment]
LGTM, thanks for your contribution!

**Comment by jefree-cat** [comment]
+1 Thanks for your contributions!

**Comment by wonderflow** [comment]
@suwliang3 Conguratulation,  you can send a PULL REQUEST to the OWNERS file.
