### ISSUE TITLE
Add @Xunzhuo as a member of KubeVela

### ISSUE THREAD

**Issue by Xunzhuo** [kubevela/community#108]
Hi community, I`d like to apply to be one of members of kubevela.

I have contributed to kubevela/catalog and added envoy-gateway as an experiment addon, and working on gateway-api trait 0.6.0 upgrade, and trying to make gateway-api related implementations (istio/envoy/traefik) to be formal by refactoring gateway-api trait and those implementations.

I would like to contribute to vela furthermore, and work on core abilities and roadmap of vela.

BTW, I am maintaining/contributing some CNCF projects and I think I can combine them with kubevela, and do something fun.

cc @wonderflow

**Comment by wonderflow** [comment]
invitation sent, thanks for your contribution.
