### ISSUE TITLE
Nominate anoop2811 as a maintainer of KubeVela Org

### ISSUE THREAD

**Issue by Somefive** [kubevela/community#110]
The Infra team of [Guidewire](https://www.guidewire.com/) has been actively participated in the KubeVela Global Community for months. The participation includes
- Frequently joined in the discussion of biweekly community meeting as recorded in https://docs.google.com/document/d/1nqdFEyULekyksFHtFvgvFAYE-0AMHKoS3RMnaKsarjs/edit#heading=h.sjr4ldygzcrb
- Multiple team members has been contributing to the code repos and raising issues under KubeVela Org. Including @anoop2811, @jamesdobson, @jguionnet, @quintonm, @ramekris3163, @motilayo, etc.
- Guidewire is one of the most representative [adopters](https://github.com/kubevela/community/blob/main/ADOPTERS.md) for KubeVela cloud resource integrations.

A short list of recent contributions from Guidewire includes:
- https://github.com/kubevela/terraform-controller/pull/352
- https://github.com/kubevela/terraform-controller/pull/349
- https://github.com/kubevela/kubevela/pull/5093
- https://github.com/kubevela/kubevela/pull/5081
- https://github.com/kubevela/kubevela/pull/5248

@anoop2811 has been leading the infra team of Guidewire, giving valuable and practical feedbacks in both the GitHub repository and Slack channel. With the whole team experienced in cloud resource management, the joining of Guidewire to the KubeVela community has provided great supports for the growth of KubeVela especially in terraform-controller.

@anoop2811 is willing to become a maintainer of KubeVela Org and continuously participates in the management and evolvement of KubeVela community. It think it will be a great help for KubeVela to get voices from a larger world-wide community. 

Welcome everyone in the KubeVela community for the voting! Feel free to share your opinion.

**Comment by wonderflow** [comment]
+1 Welcom to the community! @anoop2811

**Comment by anoop2811** [comment]
Thank you! Hoping for Guidewire to a be a helpful and valuable to the Kubevela community. And a big thanks to my team!

**Comment by jefree-cat** [comment]
+1 Welcome to the community! @anoop2811. Nice to see KubeVela production practice in Guidewire.

**Comment by FogDong** [comment]
LGTM! Guidewire has been actively involved in the community and make a big contribution to KubeVela, I'm excited to see more contributions from Guidewire!

**Comment by wonderflow** [comment]
ping @dhiguero @barnettZQG

**Comment by barnettZQG** [comment]
+1 Welcome to the community! @anoop2811. Let's work together to make the KubeVela community better.

**Comment by dhiguero** [comment]
Welcome!
