### ISSUE TITLE
Apply for membership

### ISSUE THREAD

**Issue by fengshunli** [kubevela/community#111]
Hi there, I'd like to be a member of oam community.
We are using Kubevela and have contributed five PRs.
Hope to become a Member and continue to contribute.

@wonderflow @chivalryq @Somefive

These are my contributions so far:

https://github.com/kubevela/velad/pull/113
https://github.com/kubevela/velad/pull/114
https://github.com/kubevela/velad/pull/116
https://github.com/kubevela/kubevela/pull/5417
https://github.com/kubevela/kubevela/pull/5388

**Comment by Somefive** [comment]
LGTM, good job!

**Comment by wonderflow** [comment]
invited, thanks for your contributions
