### ISSUE TITLE
Nominate FogDong as a maintainer of KubeVela Org

### ISSUE THREAD

**Issue by Somefive** [kubevela/community#114]
@FogDong has been continuously contributing to the KubeVela community for over one and a half year. She is not only one of the most active technical architects in KubeVela team, but also serves as an evangelist of OAM in the community. 

In KubeVela, she is the maintainer of a series of KubeVela core repos, including [kubevela/kubevela](https://github.com/kubevela/kubevela/), [kubevela/workflow](https://github.com/kubevela/workflow/), [kubevela/pkg](https://github.com/kubevela/pkg/), [kubevela/kube-trigger](https://github.com/kubevela/kube-trigger/). Major technical contributions are listed as below:
1. Design and maintain the workflow engine in KubeVela. The workflow engine is used in KubeVela Applications, KubeVela WorkflowRuns/Pipelines, KubeVela Triggers and VelaQL. KubeVela workflow explores the possibility of lightweight programmable execution engine on Kubernetes, based on the configuration language [CUELang](https://github.com/cue-lang/cue), and is one of the cornerstone for the build up of KubeVela.
2. Fog is one of the most experiences CUE developer and maintainer in KubeVela. Heavily using CUE in abstraction and extension, KubeVela’s evolvement is accompanied by the growth of CUE community as well. To help using CUE in KubeVela, Fog designs capabilities like `vela debug` to help KubeVela users diagnose CUE problems and consistently raises issues in the CUE community, reporting bugs and propagating concerns and problems from KubeVela users to CUE maintainers.
3. Fog also takes charge of the CI/CD integration for KubeVela in specific areas, such as GitOps, ChatOps, Image Build, Security Scan, Model Training, etc. These works greatly bridge the gaps between KubeVela and practical use cases and accelerates the adoption process of KubeVela in various scenarios. 

In addition to the technical contributions, Fog participates in a wide range of community works, including holding regular meetings, writing articles, recording tutorials, etc. She have held several KubeVela meetups in mainland China and organized multiple online world-wide sharing across the cloud native community.

With the growing and maturing of KubeVela recent days, there is an increasing number of community members willing to contribute to the KubeVela project. Here, I would like to nominate @FogDong as one of the maintainers of KubeVela in respect of the past contributions and expect her to lead more pioneering technical developments in the future.

Welcome every community member to share ideas in this issue and make votes!

**Comment by wonderflow** [comment]
+1 thanks to @FogDong for so many great contributions!

**Comment by jefree-cat** [comment]
+1, thanks for your contributions and help. @FogDong

**Comment by FogDong** [comment]
Thank you for your nomination! I will continue to contribute to this project and make it better!

**Comment by charlie0129** [comment]
+1 have seen many contributions indeed

**Comment by wonderflow** [comment]
ping @barnettZQG @dhiguero @anoop2811

**Comment by barnettZQG** [comment]
+1 can’t agree more.

**Comment by dhiguero** [comment]
Thanks for your amazing work +1

**Comment by wonderflow** [comment]
The majority(2/3) maintainers has approved, congratulations @FogDong 🎊  .

**Comment by anoop2811** [comment]
+1 totally agree
