### ISSUE TITLE
Nominate StevenLeiZhang as a maintainer of KubeVela Org

### ISSUE THREAD

**Issue by jefree-cat** [kubevela/community#128]
@StevenLeiZhang   has been leading the aPaaS team of[ JD cloud](https://www.jdcloud.com/) and making contributions in KubeVela Community.
With the leadership of @StevenLeiZhang , the whole team has involved into the whole community work from KubeVela Core repo & cli, to the ecosystem addons, along with all the documentation.
### Summary of contributions from the team:
**vela core**

- https://github.com/kubevela/kubevela/pull/3988
- https://github.com/kubevela/kubevela/pull/3981	
- https://github.com/kubevela/kubevela/pull/3928	
- https://github.com/kubevela/kubevela/pull/3852	
- https://github.com/kubevela/kubevela/pull/3851	
- https://github.com/kubevela/kubevela/pull/3787	
- https://github.com/kubevela/kubevela/pull/3636	
- https://github.com/kubevela/kubevela/pull/3501	
- https://github.com/kubevela/kubevela/pull/3345	
- https://github.com/kubevela/kubevela/pull/3275	
- https://github.com/kubevela/kubevela/pull/3122	
- https://github.com/kubevela/kubevela/pull/3109	
- https://github.com/kubevela/kubevela/pull/3099	
- https://github.com/kubevela/kubevela/pull/3358	
- https://github.com/kubevela/kubevela/pull/5274	
- https://github.com/kubevela/kubevela/pull/5246	
- https://github.com/kubevela/kubevela/pull/3358	
- https://github.com/kubevela/kubevela/pull/5568 	

**vela cli**

- https://github.com/kubevela/kubevela/pull/5534
- https://github.com/kubevela/kubevela/pull/4070
- https://github.com/kubevela/kubevela/pull/4055
- https://github.com/kubevela/kubevela/pull/4388
- https://github.com/kubevela/kubevela/pull/4239
- https://github.com/kubevela/kubevela/pull/4094
- https://github.com/kubevela/kubevela/pull/3691
- https://github.com/kubevela/kubevela/pull/3302

**x-definition**

- https://github.com/kubevela/kubevela/pull/5465	
- https://github.com/kubevela/kubevela/pull/5257	
- https://github.com/kubevela/kubevela/pull/5225	
- https://github.com/kubevela/kubevela/pull/5227	

**addon**

- https://github.com/kubevela/catalog/pull/574	
- https://github.com/kubevela/catalog/pull/347	
- https://github.com/kubevela/catalog/pull/243	

**official doc & other**

- https://github.com/kubevela/kubevela/pull/3915
- https://github.com/kubevela/kubevela.io/pull/465	
- https://github.com/kubevela/kubevela.io/pull/555	
- https://github.com/kubevela/kubevela.io/pull/611	
- https://github.com/kubevela/kubevela.io/pull/654	
- https://github.com/kubevela/kubevela.io/pull/1104	
- https://github.com/kubevela/kubevela.io/pull/655	
- https://github.com/kubevela/kubevela/pull/3791	
- https://github.com/kubevela/kubevela/pull/3781	

I think @StevenLeiZhang is willing to become the maintainer of KubeVela Org to work with other project owners to make community better. Welcome everyone in the KubeVela community for the voting! Feel free to share your opinion.

**Comment by FogDong** [comment]
LGTM! Thanks for the contribution!

**Comment by wonderflow** [comment]
+1 thanks for your great work!

**Comment by anoop2811** [comment]
+1 wecome to the community and looking forward to greater collaborations @StevenLeiZhang !

**Comment by Somefive** [comment]
LGTM! @StevenLeiZhang has been contributing to KubeVela repo for a long time and also continuously participated in review and govern the community. Welcome!

**Comment by StevenLeiZhang** [comment]
Thank you everyone!

**Comment by wonderflow** [comment]
@StevenLeiZhang Congratulations! Hope we can cooperate together to make the community larger!
