### ISSUE TITLE
Applying to be a member

### ISSUE THREAD

**Issue by howieyuen** [kubevela/community#136]
Hi there, I'd like to apply for a membership in kubevela community.

During the collaboration between kubevela and KusionStack projects, I experienced the excellent capabilities of kubevela in application operations and discovered two bugs, one of which I fixed. 

Below are my contributions so far:

https://github.com/kubevela/kubevela/issues/5662
https://github.com/kubevela/kubevela/issues/5744
https://github.com/kubevela/kubevela/pull/5745

Hope for your sponsorship 🌹,  @wonderflow @Somefive

**Comment by wonderflow** [comment]
Thank you for your contribution, but it seems that more is needed to apply for a member.

**Comment by howieyuen** [comment]
thanks for noticing

**Comment by wonderflow** [comment]
@howieyuen One or more pull requests merged will be enough! You're welcome!
