### ISSUE TITLE
Nominate @zxbyoyoyo as Approver

### ISSUE THREAD

**Issue by Somefive** [kubevela/community#145]
@zxbyoyoyo has been continuously working on multiple KubeVela's core features for a long time, including
- https://github.com/kubevela/kubevela/pull/5812
- https://github.com/kubevela/kubevela/pull/5804
- https://github.com/kubevela/kubevela/pull/4874
- https://github.com/kubevela/kubevela/pull/3468
- https://github.com/kubevela/kubevela/pull/3136
- https://github.com/kubevela/kubevela/pull/2831
- https://github.com/kubevela/kubevela/pull/2758
- https://github.com/kubevela/kubevela/pull/2731
- https://github.com/kubevela/kubevela/pull/2703

and many others.

He has also been participating in a wide range of discussions around the core capabilities of KubeVela, such as
- https://github.com/kubevela/kubevela/issues/5637
- https://github.com/kubevela/kubevela/issues/5091
- https://github.com/kubevela/kubevela/issues/4244
- https://github.com/kubevela/kubevela/issues/5457
- https://github.com/kubevela/kubevela/issues/4757
- https://github.com/kubevela/kubevela/issues/4702
- https://github.com/kubevela/kubevela/issues/3463

As an engineer in the automobile company, he also makes efforts to integrate KubeVela with GitOps and provides CD capabilities for upper layer users. With great appreciation for his contribution, I would like to nominate @zxbyoyoyo to be one of the approvers of the KubeVela community and look forward to more open communications and collaborations.

**Comment by wonderflow** [comment]
+1 thanks to @zxbyoyoyo  for so many contributions!

**Comment by zxbyoyoyo** [comment]
thank you for your recognition, I will continue to participate in kubevela's capacity building

**Comment by barnettZQG** [comment]
+1 @zxbyoyoyo is a good contributor.

**Comment by StevenLeiZhang** [comment]
+1

**Comment by wonderflow** [comment]
ping @jefree-cat @anoop2811 @dhiguero

**Comment by dhiguero** [comment]
+1

**Comment by FogDong** [comment]
LGTM! Thanks for the contributing.

**Comment by Somefive** [comment]
The nomination is accepted. @zxbyoyoyo You can raise a pull request to update the owner file and link it to this issue.
