### ISSUE TITLE
Apply for Reviewer Role

### ISSUE THREAD

**Issue by zhaohuiweixiao** [kubevela/community#148]
I would like to nominate myself as a reviewer of KubeVela.

I'd be honored if I can continue my contributions as a reviewer and committed to make the community better.

These are my contributions:
1. https://github.com/kubevela/kubevela/pull/5143
2. https://github.com/kubevela/kubevela/pull/5187
3. https://github.com/kubevela/kubevela/pull/5201
4. https://github.com/kubevela/kubevela/pull/5555
5. https://github.com/kubevela/kubevela/pull/5206
6. https://github.com/kubevela/kubevela/pull/5780
7. https://github.com/kubevela/kubevela.io/pull/1094

**Comment by wonderflow** [comment]
+1 Great job! Welcome!

**Comment by Somefive** [comment]
+1 Thanks for your contribution!

**Comment by nuclearwu** [comment]
+1 thanks for your great contributions!

**Comment by zhaohuiweixiao** [comment]
add:
https://github.com/kubevela/kubevela/pull/5865
https://github.com/kubevela/catalog/pull/684

**Comment by chivalryq** [comment]
+1 Good job!

**Comment by Hanmengnan** [comment]
+1 Good job!

**Comment by Somefive** [comment]
@zhaohuiweixiao You can raise a PR in this repo to update your role.

**Comment by zhaohuiweixiao** [comment]
> @zhaohuiweixiao You can raise a PR in this repo to update your role.

Ok, thanks for the warning.
