### ISSUE TITLE
Apply for Reviewer Role

### ISSUE THREAD

**Issue by iyear** [kubevela/community#159]
I completed the development of cue generator, doc generator and provider generator through LFX Mentorship. And I'm also interested in other components of KubeVela and hope to keep contributing in the KubeVela community.

Contributions:

- https://github.com/kubevela/kubevela/pull/5585
- https://github.com/kubevela/kubevela/pull/5720
- https://github.com/kubevela/kubevela/pull/5736
- https://github.com/kubevela/kubevela/pull/5763
- https://github.com/kubevela/kubevela/pull/5789
- https://github.com/kubevela/kubevela/pull/5795
- https://github.com/kubevela/kubevela/pull/5826
- https://github.com/kubevela/kubevela/pull/5828
- https://github.com/kubevela/kubevela/pull/5839
- https://github.com/kubevela/kubevela/pull/5893
- https://github.com/kubevela/kubevela/pull/5956
- https://github.com/kubevela/kubevela/pull/5958
- https://github.com/kubevela/kubevela/pull/5968
- https://github.com/kubevela/kubevela/pull/5975
- https://github.com/kubevela/kubevela/pull/6006
- https://github.com/kubevela/pkg/pull/45

**Comment by Somefive** [comment]
Great job! Looks good to me!

**Comment by chivalryq** [comment]
Excellent job! +1

**Comment by wonderflow** [comment]
+1 great job!

**Comment by Somefive** [comment]
@iyear You can raise a PR like #165

**Comment by iyear** [comment]
I don't seem to have received an invitation, did I miss it?

**Comment by iyear** [comment]
@Somefive I don't seem to have received an invitation, did I miss it?

**Comment by iyear** [comment]
@Somefive I don't seem to have received an invitation, did I miss it?
