### ISSUE TITLE
Apply for Reviewer Role

### ISSUE THREAD

**Issue by yyzxw** [kubevela/community#167]
I refactored part of the vela-controller code, improved the controller's startup speed,and expose some helm chart paramters, also added some unit test coverage.And I'm also interested in other components of KubeVela and hope to keep contributing in the KubeVela community.

Contributions:
- https://github.com/kubevela/kubevela/pull/6060
- https://github.com/kubevela/kubevela/pull/6044
- https://github.com/kubevela/kubevela/pull/6043
- https://github.com/kubevela/kubevela/pull/6012
- https://github.com/kubevela/kubevela/pull/6017
- https://github.com/kubevela/kubevela/pull/6007
- https://github.com/kubevela/kubevela/pull/5986
- https://github.com/kubevela/kubevela/pull/5985
- https://github.com/kubevela/community/pull/163

Discussions:
- https://github.com/kubevela/kubevela/issues/6062
- https://github.com/kubevela/kubevela/issues/5605

**Comment by Somefive** [comment]
Great job! +1

**Comment by Hanmengnan** [comment]
LGTM

**Comment by wonderflow** [comment]
+1 thanks for your great work!

**Comment by Somefive** [comment]
Thanks for the great work!
