### ISSUE TITLE
Jun 14, 2022 Community Meeting Agenda (中文社区会议)

### ISSUE THREAD

**Issue by zzxwill** [kubevela/community#17]
KubeVela Community Meetings

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the KubeVela community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the KubeVela community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on Tuesday, June 14, 2022 19:00 PM China Standard Time (CST). The meeting agenda will be finalized by a Community Call Host days prior to the meeting.

Thank you and we look forward to hearing your input.

| Asset | Link        |
|:-----------|:------------|
| 🔗 Meeting Link & Password (*中文社区*) | **Zoom Call:** https://us02web.zoom.us/j/88035629406<br>**Password:** OWp2TlNqM0NjUjhoTlF6eGZMNURuZz09
| 🎥 Meeting Recordings (*中文社区*) | https://space.bilibili.com/180074935/channel/seriesdetail?sid=1842207
| Meeting time | Tuesday Jun 14th, 2022 19:00 PM China Standard Time (CST)  - [See it in your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20220614T04&p1=234)

欢迎使用中文留言或交流，此会议也全程使用中文沟通。 (This meeting will use Chinese to negotiate.)

**Comment by wangyikewxgm** [comment]
@jefree-cat will give a introduction about a proposal of observablity and SLO Ref: https://github.com/kubevela/community/issues/8#issuecomment-1140992479

**Comment by Alpacius** [comment]
Discussions about multicluster concurrent reconciliation performance and related horizontal scaling issues.

### Backgrounds:
Assume that we, as CICD platform owners & developers, would like to host one or more control plane cluster(s) with KubeVela core & gateway controller to delivery applications to our external customers. It is likely that we have to vela-cluster-join customers' data plane clusters, which are usually not a small number, and put ourselves under such situation where burst of concurrent reconcile on OAM applications is the common case.

Increasing concurrentReconciles may be the viable workaround solution for now. However, considering that usage of a independent control plane, especially its worker nodes, may be further extended by introducing more horizontal scaling mechanisms.

---

有关vela-core controller在多集群部署场景下的并发性能&水平性能扩增讨论。

### 背景：
考虑一种业务场景：CICD平台的开发者，希望通过自持（一个或多个）部署了KubeVela相关控制器的控制面集群，为平台的外部客户提供应用交付能力。这种情况下，客户的数据面集群将会join到控制面集群上（因为是对外业务，量级通常不会是数个或是十数个这样的小规模），且通常会伴随客户的发布节奏产生较明显的OAM application调谐并发量尖峰。

临时解决方案可能是直接增大控制器的concurrentReconciles，但考虑到单点并发的扩增量瓶颈总在apiserver，单纯调谐的方式可能也无法充分利用控制面集群的worker节点，希望能够探讨KubeVela在此类有性能水平扩增诉求场景下的实践方式。
