### ISSUE TITLE
Apply for Reviewer Role

### ISSUE THREAD

**Issue by NeerajGartia21** [kubevela/community#175]
I would like to nominate myself as a reviewer of KubeVela.

I'm contributing to VelaUX in expanding its database drivers for MySQL and PostgreSQL as a part of LFX mentorship program. And I'm also interested in other components of KubeVela and hope to keep contributing in the KubeVela community.

These are my contributions :

- https://github.com/kubevela/velaux/pull/841
- https://github.com/kubevela/velaux/pull/825
- https://github.com/kubevela/velaux/pull/797
- https://github.com/kubevela/velaux/pull/711
- https://github.com/kubevela/velaux/pull/821
- https://github.com/kubevela/velaux/pull/836
- https://github.com/kubevela/velaux/pull/849
- https://github.com/kubevela/kubevela.github.io/pull/1239

**Comment by wonderflow** [comment]
great job! Thanks for your contributions!

+1

**Comment by chivalryq** [comment]
Nice job! Welcome to community!

+1

**Comment by FogDong** [comment]
LGTM! Thanks for the contribution!

**Comment by chivalryq** [comment]
@NeerajGartia21 You can open a PR in community repo and add yourself to reviewers like https://github.com/kubevela/community/pull/172
