### ISSUE TITLE
Nominate @chivalryq and @wangyikewxgm  as Maintainer 

### ISSUE THREAD

**Issue by wonderflow** [kubevela/community#180]
@chivalryq and @wangyikewxgm  have been as approver members for a long time .

- @chivalryq is the creator of [velad](https://github.com/kubevela/velad) project.
- @wangyikewxgm is the creator of addon mechanism and maintain the [catalog](https://github.com/kubevela/catalog).

They both maintain the kubevela ecosystem projects for long time.

I think they're qualified as maintainers!

**Comment by Somefive** [comment]
+1 Great job!

**Comment by jefree-cat** [comment]
+1 Great job!

**Comment by FogDong** [comment]
LGTM!

**Comment by dhiguero** [comment]
+1

**Comment by StevenLeiZhang** [comment]
+1

**Comment by anoop2811** [comment]
+1

**Comment by anoop2811** [comment]
+1

**Comment by chivalryq** [comment]
I'm very honored and excited for being nominated as the maintainer of KubeVela. I'd like to do my best to make KubeVela better!

**Comment by wangyikewxgm** [comment]
Thanks for the nomination as KubeVela Maintainer. I gladly accept the opportunity to contribute further.

**Comment by wonderflow** [comment]
Congratulations! Most of our maintainers have voted for approval!

@chivalryq Would you like to send a PR for this？

**Comment by chivalryq** [comment]
> Congratulations! Most of our maintainers have voted for approval!
> 
> @chivalryq Would you like to send a PR for this？

OK. I'd like to.

**Comment by chivalryq** [comment]
PR created: https://github.com/kubevela/community/pull/182
