### ISSUE TITLE
Apply for Approver Role

### ISSUE THREAD

**Issue by suwliang3** [kubevela/community#189]
I would like to nominate myself as a Approver of KubeVela.

I'd be honored if I can continue my contributions as a approver and committed to make the community better.

These are my contributions:
pull requests:

1. [https://github.com/kubevela/kubevela/pull/5189](https://github.com/kubevela/kubevela/pull/5189)
2. [https://github.com/kubevela/kubevela/pull/5202](https://github.com/kubevela/kubevela/pull/5202)
3. [https://github.com/kubevela/kubevela/pull/5221](https://github.com/kubevela/kubevela/pull/5221)
4. [https://github.com/kubevela/kubevela/pull/5325](https://github.com/kubevela/kubevela/pull/5325)
5. https://github.com/kubevela/kubevela/pull/5497
6. https://github.com/kubevela/kubevela/pull/5559
7. https://github.com/kubevela/kubevela/pull/5646
8. https://github.com/kubevela/kubevela/pull/5924
9. https://github.com/kubevela/kubevela/pull/6096
10. https://github.com/kubevela/kubevela/pull/6207
11. https://github.com/kubevela/kubevela/pull/6256
12. https://github.com/kubevela/kubevela/pull/6288
13. https://github.com/kubevela/catalog/pull/563
14. https://github.com/kubevela/catalog/pull/570
15. https://github.com/kubevela/catalog/pull/580
16. https://github.com/kubevela/catalog/pull/662
17. https://github.com/kubevela/kubevela.github.io/pull/1082
18. https://github.com/kubevela/kubevela/pull/6257

issues:

1. https://github.com/kubevela/kubevela/issues/6208
2. https://github.com/kubevela/kubevela/issues/6244
3. https://github.com/kubevela/kubevela/issues/6331
4. https://github.com/kubevela/kubevela/issues/5148
5. https://github.com/kubevela/kubevela/issues/5214
6. https://github.com/kubevela/kubevela/issues/5324
7. https://github.com/kubevela/kubevela/issues/5467
8. https://github.com/kubevela/kubevela/issues/5556
9. https://github.com/kubevela/kubevela/issues/5645
10. https://github.com/kubevela/kubevela/issues/5750
11. https://github.com/kubevela/kubevela/issues/6092
12. https://github.com/kubevela/kubevela/issues/6206
13. https://github.com/kubevela/kubevela/issues/6255
14. https://github.com/kubevela/kubevela/issues/6289
15. https://github.com/kubevela/kubevela/issues/6327
16. https://github.com/kubevela/catalog/issues/569
17. https://github.com/kubevela/catalog/issues/576

code reviews:

1. https://github.com/kubevela/kubevela/pull/6273
2. https://github.com/kubevela/catalog/pull/725

**Comment by chivalryq** [comment]
Thanks for contribution! Hopefully you can contribute more on code reviewing in the future. +1

**Comment by dhiguero** [comment]
+1

**Comment by wonderflow** [comment]
+1 thanks for your great work!

**Comment by anoop2811** [comment]
+1

**Comment by FogDong** [comment]
LGTM, thanks for the contribution!
