### ISSUE TITLE
Apply for Reviewer Role

### ISSUE THREAD

**Issue by caiqi1111** [kubevela/community#199]
I would like to nominate myself as a reviewer of KubeVela.

These are my contributions :

https://github.com/kubevela/kubevela/pull/6355
https://github.com/kubevela/kubevela/pull/6352
https://github.com/kubevela/kubevela/pull/6015
https://github.com/kubevela/kubevela/pull/5786
https://github.com/kubevela/kubevela/pull/5547
https://github.com/kubevela/kubevela/pull/5535
https://github.com/kubevela/velaux/pull/698

**Comment by wonderflow** [comment]
+1 thanks for your contributions!

**Comment by anoop2811** [comment]
+1

**Comment by nuclearwu** [comment]
+1

**Comment by nuclearwu** [comment]
+1
