### ISSUE TITLE
Jun 28, 2022 Community Meeting Agenda (中文社区会议) 

### ISSUE THREAD

**Issue by wangyikewxgm** [kubevela/community#24]
KubeVela Community Meetings

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the KubeVela community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the KubeVela community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on Tuesday, June 28, 2022 19:00 PM China Standard Time (CST). The meeting agenda will be finalized by a Community Call Host days prior to the meeting.

Thank you and we look forward to hearing your input.

| Asset | Link        |
|:-----------|:------------|
| 🔗 Meeting Link & Password (*中文社区*) | **Zoom Call:** https://us02web.zoom.us/j/88035629406<br>**Password:** OWp2TlNqM0NjUjhoTlF6eGZMNURuZz09
| 🎥 Meeting Recordings (*中文社区*) | https://space.bilibili.com/180074935/channel/seriesdetail?sid=1842207
| Meeting time | Tuesday Jun 28th, 2022 19:00 PM China Standard Time (CST)  - [See it in your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20220628T04&p1=234)

欢迎使用中文留言或交流，此会议也全程使用中文沟通。 (This meeting will use Chinese to negotiate.)

**Comment by zzxwill** [comment]
会议议题：
- 工作流的新功能 demo: 包括子步骤，if 条件判断，超时，暂停自动继续等。 10-20 分钟
- KubeVela 云资源支持 Crossplane 简介 5 分钟

**Comment by FogDong** [comment]
> 社区会议问题： Q1: 期望 component 失败的问题早于 component 部署尝试的时间结束前就暴露出来 通过自己写 WorkflowStep，调用 op.failed，快速暴露失败问题。
> 
> Q2：支持 workflowstep 组吗？ 支持，雾雾已分享
> 
> Q3：Crossplane addon 是否支持阿里云 目前不支持，只支持 AWS

关于 Q2 的补充：
1. 使用 step-group 为步骤分组
2. 可以通过 if 条件判断来判断当前步骤是否需要执行，在 if 中可以通过 `status` 找到其他步骤的状态，具体可以参考 [文档](https://kubevela.io/zh/docs/next/end-user/workflow/if-condition)。

**Comment by wonderflow** [comment]
delivered https://space.bilibili.com/180074935/channel/seriesdetail?sid=1842207
