### ISSUE TITLE
Apply for membership

### ISSUE THREAD

**Issue by Arhell** [kubevela/community#25]
Hi there, I'd like to be a member of oam community.
bug fixes and site support
сс @wonderflow

**Comment by wonderflow** [comment]
invited, please confirm. Thanks for your great work!

**Comment by wonderflow** [comment]
BTW, would you like to finish the rest part of the logo in the dark mode:

![image](https://user-images.githubusercontent.com/2173670/171541565-87eefd1c-71fa-468b-8f98-9399203708f7.png)
