### ISSUE TITLE
Apply for Approver Role

### ISSUE THREAD

**Issue by StevenLeiZhang** [kubevela/community#26]
I apply for Approver role of repo kubevela.
Have 22 PRs totally for  all of the repos so far.

**Comment by wonderflow** [comment]
great, thanks for all your contributions!

+1 from myside!

**Comment by leejanee** [comment]
great, thanks for all your contributions!

**Comment by wangyikewxgm** [comment]
Thanks your contributions for addon and other areas! +1

**Comment by FogDong** [comment]
Steven has been very active in the community, I think he can be a qualified approver.
LGTM and thanks for the contributions!

**Comment by wonderflow** [comment]
Since there're a majority votes for approval! Congratulations! @StevenLeiZhang

**Comment by barnettZQG** [comment]
Great! I see you are active in multiple areas of KubeVela. Looking forward to more proposals and contributions from you.

+1 from myside!

**Comment by barnettZQG** [comment]
Since there're two Maintainers vote for approval, according to our community rules, congratulations! @StevenLeiZhang
