### ISSUE TITLE
Norminate @Arhell  to be a reviewer member of KubeVela Org

### ISSUE THREAD

**Issue by wonderflow** [kubevela/community#33]
@Arhell has made consistent contributions on kubevela.io, [his contribution](https://github.com/kubevela/kubevela.io/pulls?q=is%3Apr+author%3AArhell+is%3Aclosed) is already [qualified to be a reviewer member](https://github.com/kubevela/community/blob/main/community-membership.md).

I think he'll be glad to continue his contribution as a reviewer member! \cc @Arhell 

Anyone who agree with me, please help vote on this issue. Thanks.

**Comment by wonderflow** [comment]
ping @Arhell Would you like to become a reviewer member of KubeVela?

**Comment by Arhell** [comment]
> ping @Arhell Would you like to become a reviewer member of KubeVela?

I don't mind, but I mainly deal with the front-end, so I will rather only deal with the site.

**Comment by wonderflow** [comment]
Yes, it's fine to review only the website.

**Comment by Somefive** [comment]
LGTM

**Comment by barnettZQG** [comment]
Maybe you could care about the [VelaUX](https://github.com/kubevela/velaux) project and improve it. LGTM

Since there're two Maintainers who vote for approval, according to our community rules, congratulations! @Arhell

**Comment by barnettZQG** [comment]
@Arhell Please commit a PR to add your name to the owner's list.

**Comment by FogDong** [comment]
LGTM, thanks for the contribution!🎉
