### ISSUE TITLE
July 12, 2022 Community Meeting Agenda (中文社区会议)

### ISSUE THREAD

**Issue by wonderflow** [kubevela/community#34]
KubeVela Community Meetings

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the KubeVela community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the KubeVela community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on Tuesday, July 12, 2022 19:00 PM China Standard Time (CST). The meeting agenda will be finalized by a Community Call Host days prior to the meeting.

Thank you and we look forward to hearing your input.

| Asset | Link        |
|:-----------|:------------|
| 🔗 Meeting Link & Password (*中文社区*) | **Zoom Call:** https://us02web.zoom.us/j/88638962723?pwd=MVhCZnNub2t0R3BmMUNEWE9vendLUT09
| 🎥 Meeting Recordings (*中文社区*) | https://space.bilibili.com/180074935/channel/seriesdetail?sid=1842207
| Meeting time | Tuesday July 12th, 2022 19:00 PM China Standard Time (CST)  - [See it in your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20220712T04&p1=234)

欢迎使用中文留言或交流，此会议也全程使用中文沟通。 (This meeting will use Chinese to negotiate.)

**Comment by wangyikewxgm** [comment]
I'm happy to give an introduction and demo for application canary rollout.

**Comment by charlie0129** [comment]
I'm willing to will give a demo about using ChartMuseum as an addon registry and related `vela addon push` commands.
