### ISSUE TITLE
Norminate @charlie0129 to be a reviewer member of KubeVela Org

### ISSUE THREAD

**Issue by wonderflow** [kubevela/community#38]
He has contributed a lot of powerful features to kubevela repo!

https://github.com/kubevela/kubevela/commits?author=charlie0129

I think he'll be glad to continue his contribution as a reviewer member! \cc @charlie0129

Anyone who agree with me, please help vote on this issue. Thanks.

**Comment by charlie0129** [comment]
Yes, it's my honor to become a review member, with more contributions to come!

**Comment by yangsoon** [comment]
lgtm

**Comment by Somefive** [comment]
LGTM

**Comment by barnettZQG** [comment]
LGTM

Since there're two Maintainers vote for approval, according to our community rules, congratulations! @charlie0129

**Comment by wangyikewxgm** [comment]
Thanks for lots of great works.  Congratulations! @charlie0129!
