### ISSUE TITLE
Norminate ZhongsJie96 as a reviewer member of KubeVela Org

### ISSUE THREAD

**Issue by wonderflow** [kubevela/community#43]
@ZhongsJie96 has contributed lots of features and proposals to kubevela!

* PRs:  https://github.com/kubevela/kubevela/commits?author=ZhongsJie96
* Ideas: https://github.com/kubevela/kubevela/issues?q=+is%3Aissue+author%3AZhongsJie96+

I think he'll be glad to continue his contribution as a reviewer member! \cc @ZhongsJie96

Anyone who agree with me, please help vote on this issue. Thanks.

**Comment by zhaopei05** [comment]
He is a sexy guy.

**Comment by ZhongsJie96** [comment]
Thanks to the community, there is a link error here, it should be https://github.com/kubevela/kubevela/commits?author=ZhongsJie96, I will actively devote myself to community building in the future.

**Comment by wonderflow** [comment]
> Thanks to the community, there is a link error here, it should be https://github.com/kubevela/kubevela/commits?author=ZhongsJie96, I will actively devote myself to community building in the future.

Sorry, I've updated

**Comment by FogDong** [comment]
LGTM, thanks for the contributing!

**Comment by yangsoon** [comment]
LGTM

**Comment by wangyikewxgm** [comment]
LGTM

**Comment by barnettZQG** [comment]
LGTM, welcome to join the KubeVela family!

@ZhongsJie96 Since there're more than two Maintainers who vote for approval, according to our community rules, congratulations! 

Please commit a PR to add your name and company to the reviewer list.
