### ISSUE TITLE
Norminate jefree-cat as a maintainer of KubeVela Org

### ISSUE THREAD

**Issue by wonderflow** [kubevela/community#44]
The Cloud Infra Develop team of [China Merchants Bank](https://www.cmbchina.com/) has become partner of KubeVela Community, while @jefree-cat is the Leader & Coordinator of the team! The team member including:

- @fourierr   reviewer member of KubeVela Org
- @oeular reviewer member of KubeVela Org
- @ZhongsJie96  memeber of KubeVela Org
- @zq200618  member of  KubeVela Org
- @ivyilike contributor of KubeVela Org
- @oiar controbutor of KubeVela Org

With the leadership of  @jefree-cat , the whole team has involved into the whole community work from KubeVela Core repo, to the ecosystem addons, along with all the documentation.

@jefree-cat has a deep understanding of the technical details and share the same goals of KubeVela. He's also very experienced on the modern cloud native application delivery and management.

I think @jefree-cat  is willing to become the maintainer of KubeVela Org to work with other project owners to maintain the project's overall health and success holistically.

**Comment by zhaopei05** [comment]
He is more than sexy!

**Comment by zhaopei05** [comment]
Couldn't be more sexy!

**Comment by oeular** [comment]
Come to be better !

**Comment by redhander** [comment]
great,keep going

**Comment by jefree-cat** [comment]
Thanks to the community for the nomination. Congratulation! It's honor of the team. Besides above team contributor, The team includes @oeular @oiar @pengchen1989 @fzyleft @zq200618  @ZhongsJie96  @zq200618 @ivyilike @cdy-cmbnt. Really respect and appreciate their teamwork and hard work for community and product. Next, will contribute more ideas, proposals and solutions to the community based on our product engineering practice. Collaborate with community colleagues to support vela from sandbox to incubating project. @wonderflow @barnettZQG  @Somefive @yangsoon @FogDong

**Comment by FogDong** [comment]
LGTM! Thanks for the contribution and welcome to the community!

**Comment by pengchen1989** [comment]
I am honored to be mentioned by @jefree-cat  and join the community

**Comment by cdy-cmbnt** [comment]
@jefree-cat   GOOD BOY,  work together

**Comment by chivalryq** [comment]
Welcome to the community!

**Comment by barnettZQG** [comment]
@jefree-cat Enjoy popular confidence, welcome to become a maintainer. According to the rules of the community, welcome to make the planning of the KubeVela project, the realization of important features, and participation in organizing community meetings. 

Announced only on behalf of the community, officially accepting @jefree-cat  as maintainer.

**Comment by Somefive** [comment]
Looking forward to more collaborations!

**Comment by jefree-cat** [comment]
> @jefree-cat You can raise a pull request not, as 2/3 maintainers have sponsored

slo implementation will pr next
