### ISSUE TITLE
May 10, 2022 Community Meeting Agenda

### ISSUE THREAD

**Issue by wonderflow** [kubevela/community#5]
KubeVela Community Meetings

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the KubeVela community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the KubeVela community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on Tuesday May 10, 2022 07:30 AM PST. The meeting agenda will be finalized by a Community Call Host days prior to the meeting.

Thank you and we look forward to hearing your input.

| Asset | Link        |
|:-----------|:------------|
| 🔗 Meeting Link & Password (*English*) | **Zoom Call:** https://us02web.zoom.us/j/88638962723<br>**Password:** MVhCZnNub2t0R3BmMUNEWE9vendLUT09
| 🎥 Meeting Recordings (*English*) | https://docs.google.com/document/d/1nqdFEyULekyksFHtFvgvFAYE-0AMHKoS3RMnaKsarjs
| Meeting time | Tuesday May 10, 2022 07:30 AM Pacific Time (PST) - [See it in your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20220510T0730&p1=234)

**Comment by Somefive** [comment]
Agenda.
1. Introduction to the Community Meeting Agenda mechanism.
2. Brief introduction to the key features in the KubeVela v1.4. (velad & auth)
3. Discussion to the deploy of cloud-resource. Should its management be separately treated or unified treated?

Attachment
![image](https://user-images.githubusercontent.com/14019297/167628798-2b7f3d0a-ea74-4de0-a8e8-3204bb179564.png)
![image](https://user-images.githubusercontent.com/14019297/167628766-78aa9422-0ffd-4aad-903c-bdc4b7110e47.png)

**Comment by Somefive** [comment]
helm install kubevela ./charts/vela-core --create-namespace -n vela-system --wait --debug --set image.tag=v1.4.0-alpha.2 --set authentication.enabled=true

**Comment by wonderflow** [comment]
delivered
