### ISSUE TITLE
Aug 9, 2022 Community Meeting Agenda (中文社区会议)

### ISSUE THREAD

**Issue by wonderflow** [kubevela/community#54]
KubeVela Community Meetings

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the KubeVela community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the KubeVela community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call. The meeting agenda will be finalized by a Community Call Host days prior to the meeting.

Thank you and we look forward to hearing your input.

| Asset | Link        |
|:-----------|:------------|
| 🔗 Meeting Link & Password (*中文社区*) | **Zoom Call:** https://us02web.zoom.us/j/88638962723?pwd=MVhCZnNub2t0R3BmMUNEWE9vendLUT09
| 🎥 Meeting Recordings (*中文社区*) | https://space.bilibili.com/180074935/channel/seriesdetail?sid=1842207
| Meeting time | Tuesday Aug 9, 2022 19:00 PM China Standard Time (CST)  - [See it in your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20220809T04&p1=234)

欢迎使用中文留言或交流，此会议也全程使用中文沟通。 (This meeting will use Chinese to negotiate.)

@barnettZQG   是本次会议的主持人。

**Comment by lipingtababa** [comment]
招商分享案例的时候, 如果可以多介绍下团队分工, 会更有助于听众理解他们的workflow.  具体的说, 谁来撰写pipeline, 谁来确定pipeline的steps, 谁来撰写vela的workflow模版.

**Comment by LeoLiuYan** [comment]
就用中文了哈~
问题：
1.  Mono Repo在刚才的CI Spec里是不是没办法跑？   @招行同学

**Comment by jefree-cat** [comment]
> 就用中文了哈~ @招行同学 问题：
> 
> 1. Mono Repo在刚才的CI Spec里是不是没办法跑？

进社区群交流

**Comment by jefree-cat** [comment]
> 招商分享案例的时候, 如果可以多介绍下团队分工, 会更有助于听众理解他们的workflow. 具体的说, 谁来撰写pipeline, 谁来确定pipeline的steps, 谁来撰写vela的workflow模版.

社区群交流

**Comment by barnettZQG** [comment]
视频回放：https://www.bilibili.com/video/BV1xa411P7hr
