### ISSUE TITLE
Self-nominate @charlie0129 as approver

### ISSUE THREAD

**Issue by charlie0129** [kubevela/community#58]
I would like to nominate myself as an approver of KubeVela and get involved in more aspects of the project in the future. 

I'd be honored if I can continue my contributions as an approver and committed to make the community better.

---

These are my contributions from May, 2022 to July, 2022.

> The following information is fetched using GitHub API, most-recent ones first.

### Submitted PRs

1. https://github.com/kubevela/kubevela/pull/4473
2. https://github.com/kubevela/kubevela/pull/4472
3. https://github.com/kubevela/catalog/pull/422
4. https://github.com/kubevela/kubevela/pull/4434
5. https://github.com/kubevela/kubevela/pull/4433
6. https://github.com/kubevela/kubevela.io/pull/874
7. https://github.com/kubevela/kubevela/pull/4415
8. https://github.com/kubevela/kubevela.io/pull/858
9. https://github.com/kubevela/catalog/pull/408
10. https://github.com/kubevela/kubevela/pull/4370
11. https://github.com/kubevela/catalog/pull/402
12. https://github.com/kubevela/kubevela.io/pull/836
13. https://github.com/kubevela/kubevela/pull/4324
14. https://github.com/kubevela/kubevela.io/pull/827
15. https://github.com/kubevela/kubevela/pull/4309
16. https://github.com/kubevela/kubevela/pull/4307
17. https://github.com/kubevela/catalog/pull/396
18. https://github.com/kubevela/kubevela/pull/4290
19. https://github.com/kubevela/velaux/pull/559
20. https://github.com/kubevela/catalog/pull/393
21. https://github.com/kubevela/kubevela.io/pull/793
22. https://github.com/kubevela/kubevela.io/pull/792
23. https://github.com/kubevela/kubevela/pull/4261
24. https://github.com/kubevela/kubevela.io/pull/766
25. https://github.com/kubevela/kubevela.io/pull/764
26. https://github.com/kubevela/kubevela/pull/4166
27. https://github.com/kubevela/kubevela/pull/4166
28. https://github.com/kubevela/kubevela/pull/4156
29. https://github.com/kubevela/kubevela/pull/4141
30. https://github.com/kubevela/community/pull/30
31. https://github.com/kubevela/kubevela.io/pull/714
32. https://github.com/kubevela/catalog/pull/370
33. https://github.com/kubevela/kubevela/pull/4126
34. https://github.com/kubevela/kubevela/pull/3876
35. https://github.com/kubevela/kubevela/pull/3827
36. https://github.com/kubevela/catalog/pull/342

### Reviewed PRs

1. https://github.com/kubevela/kubevela/pull/4473
2. https://github.com/kubevela/kubevela/pull/4449
3. https://github.com/kubevela/catalog/pull/418
4. https://github.com/kubevela/kubevela/pull/4434
5. https://github.com/kubevela/kubevela.io/pull/871
6. https://github.com/kubevela/kubevela/pull/4422
7. https://github.com/kubevela/kubevela/pull/4415
8. https://github.com/kubevela/catalog/pull/412
9. https://github.com/kubevela/kubevela/pull/4401
10. https://github.com/kubevela/kubevela/pull/4398
11. https://github.com/kubevela/kubevela/pull/4388
12. https://github.com/kubevela/kubevela/pull/4379
13. https://github.com/kubevela/kubevela/pull/4370
14. https://github.com/kubevela/kubevela.io/pull/846
15. https://github.com/kubevela/kubevela/pull/4346
16. https://github.com/kubevela/catalog/pull/402
17. https://github.com/kubevela/kubevela/pull/4324
18. https://github.com/kubevela/kubevela.io/pull/830
19. https://github.com/kubevela/kubevela/pull/4282
20. https://github.com/kubevela/kubevela.io/pull/820
21. https://github.com/kubevela/kubevela.io/pull/797
22. https://github.com/kubevela/kubevela/pull/4261
23. https://github.com/kubevela/kubevela.io/pull/766
24. https://github.com/kubevela/kubevela/pull/4162
25. https://github.com/kubevela/kubevela/pull/4156
26. https://github.com/kubevela/kubevela/pull/4146
27. https://github.com/kubevela/kubevela/pull/4142
28. https://github.com/kubevela/kubevela/pull/4133
29. https://github.com/kubevela/kubevela/pull/4126
30. https://github.com/kubevela/kubevela/pull/3876

### Assigned Issues

1. https://github.com/kubevela/kubevela/issues/4268
2. https://github.com/kubevela/kubevela/issues/4235
3. https://github.com/kubevela/kubevela.io/issues/758
4. https://github.com/kubevela/kubevela/issues/4163
5. https://github.com/kubevela/kubevela/issues/4140
6. https://github.com/kubevela/kubevela/issues/4131
7. https://github.com/kubevela/kubevela/issues/3860
8. https://github.com/kubevela/kubevela/issues/3583

### Involved Issues

1. https://github.com/kubevela/kubevela/issues/4407
2. https://github.com/kubevela/kubevela/issues/4317
3. https://github.com/kubevela/kubevela/issues/4311
4. https://github.com/kubevela/kubevela/issues/4288
5. https://github.com/kubevela/community/issues/38
6. https://github.com/kubevela/kubevela.io/issues/814
7. https://github.com/kubevela/kubevela/issues/4271
8. https://github.com/kubevela/kubevela/issues/4268
9. https://github.com/kubevela/kubevela/issues/4235
10. https://github.com/kubevela/community/issues/34
11. https://github.com/kubevela/kubevela.io/issues/758
12. https://github.com/kubevela/kubevela/issues/4163
13. https://github.com/kubevela/kubevela/issues/4140
14. https://github.com/kubevela/kubevela/issues/4131
15. https://github.com/kubevela/catalog/issues/368
16. https://github.com/kubevela/kubevela/issues/4122
17. https://github.com/kubevela/kubevela/issues/3860
18. https://github.com/kubevela/kubevela/issues/3856
19. https://github.com/kubevela/kubevela/issues/3583
20. https://github.com/kubevela/kubevela/issues/3219

**Comment by wonderflow** [comment]
Cool!!!! It's really great to see so much contributions!

**Comment by Somefive** [comment]
Great job!

**Comment by wangyikewxgm** [comment]
Incredible contributions. +1

**Comment by chivalryq** [comment]
Amazing contribution! Good job!

**Comment by FogDong** [comment]
Thank you for your contributions!

**Comment by jefree-cat** [comment]
impressed contribution！congratulation！+1
