### ISSUE TITLE
May 17, 2022 Community Meeting Agenda (中文社区会议)

### ISSUE THREAD

**Issue by wonderflow** [kubevela/community#6]
KubeVela Community Meetings

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the KubeVela community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the KubeVela community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on Tuesday May 10, 2022 07:30 AM PST. The meeting agenda will be finalized by a Community Call Host days prior to the meeting.

Thank you and we look forward to hearing your input.

| Asset | Link        |
|:-----------|:------------|
| 🔗 Meeting Link & Password (*中文社区*) | **Zoom Call:** https://us02web.zoom.us/j/88035629406<br>**Password:** OWp2TlNqM0NjUjhoTlF6eGZMNURuZz09
| 🎥 Meeting Recordings (*中文社区*) | https://space.bilibili.com/180074935/channel/seriesdetail?sid=1842207
| Meeting time | Tuesday May 17, 2022 19:00 PM China Standard Time (CST)  - [See it in your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20220517T04&p1=234)

欢迎使用中文留言或交流，此会议也全程使用中文沟通。 (This meeting will use Chinese to negotiate.)

**Comment by oeular** [comment]
用户自定义的Trait Controller会越来越多，而且即将到来的版本也支持指定集群部署Trait CR，那么所有的CR controller就面临同样的一个问题：如何开发controller的多集群能力，比如如何“标准化”地控制业务集群资源。
所以，我们希望vela自身的多集群管理能力可以通过一种“配置的方式”赋能给用户自定义的Controller。一方面降低用户开发controller的成本，另一方面也充分利用cluster-gateway的能力。

**Comment by Somefive** [comment]
> 用户自定义的Trait Controller会越来越多，而且即将到来的版本也支持指定集群部署Trait CR，那么所有的CR controller就面临同样的一个问题：如何开发controller的多集群能力，比如如何“标准化”地控制业务集群资源。 所以，我们希望vela自身的多集群管理能力可以通过一种“配置的方式”赋能给用户自定义的Controller。一方面降低用户开发controller的成本，另一方面也充分利用cluster-gateway的能力。

This is a good idea. Although proposals are lack for now temporarily, it appears to be a worthy topic to discussion. I suggest open an issue to discuss it in details and share the link here. Would you like to translate this proposal into English and post it in an issue in kubevela/kubevela?

**Comment by wonderflow** [comment]
1. 介绍 community repo 的情况，包括 1）社区成员晋级机制； 2）adopters 文件。
2. 介绍 velad 的内容，demo

**Comment by zzxwill** [comment]
- KubeVela reviewers 颁奖 @BinaryHB0916 
- KubeVela 社区成员晋级机制 @zzxwill 
- velad demo 中沛

**Comment by zzxwill** [comment]
Q&A

- 之前在群里讨论的更原生的支持k8s原生资源,这个是什么计划呢
这里有两种设想，看大家怎么看：

1. 从 Deployment 迁移到 App 后，后续的 CD 以 App 属性修改为唯一入口，完全托管。
2. 后续还可以继续通过修改 Deployment 和 App 来进行发布。

补充：用户目前已经通过 ref-object 实现 KubeVela 接管

建议：创建一个 issue 继续跟踪讨论，原则上保留一个管理入口。
