### ISSUE TITLE
Apply for membership

### ISSUE THREAD

**Issue by nuclearwu** [kubevela/community#85]
Hi guys. I'd like to be a member of KubeVela community. I have contributed some PRs to KubeVela community.
Hope to become a Member and continue to contribute.
Thanks!

These are my contributions so far:

1、[Fix: Failed to get detail policy for application #5043](https://github.com/kubevela/kubevela/pull/5043
)
2、[Feat: support field selector filter for 'vela ls' #5016](https://github.com/kubevela/kubevela/pull/5016
)
3、[Fix: vela cluster join reports 'resource name may not be empty' error #4998](https://github.com/kubevela/kubevela/pull/4998)
4、[Feat: support label selector filter for 'vela ls' #4966](https://github.com/kubevela/kubevela/pull/4966
)
5、[Fix: update namespace only if it doesn't have the env label #4947](https://github.com/kubevela/kubevela/pull/4947
)
6、[Feat: support dryrun operation when creating or updating applications #4860](https://github.com/kubevela/kubevela/pull/4860
)
7、[Fix: it does not check the same name for 'vela env init' #4796](https://github.com/kubevela/kubevela/pull/4796)

**Comment by wonderflow** [comment]
Great job! +1

**Comment by wonderflow** [comment]
ping @Somefive @FogDong @jefree-cat @barnettZQG

**Comment by FogDong** [comment]
LGTM, thanks for contributing!

**Comment by barnettZQG** [comment]
@nuclearwu According to our community rules, Wellcome to as a Reviewer. We are looking forward to more contributions.  The next role is [Approver](https://github.com/kubevela/community/blob/main/community-membership.md#approver).

**Comment by wonderflow** [comment]
@nuclearwu Congratulations! According to our community rule, you've been supported by three Maintainer/Approvers. You can create a PR to add yourself.

**Comment by nuclearwu** [comment]
Thanks everyone, I appreciate it!

**Comment by jefree-cat** [comment]
Great Job! Welcome!

**Comment by nuclearwu** [comment]
@wonderflow Could you please invite me to be a member?
